name: Search.digitalgov.gov
description: 'The website for the DigitalGov Search program'
license: null
openSourceProject: 1
governmentWideReuseProject: 0
tags:
    - GSA
    - DigitalGovSearch
    - search
    - website
contact:
    email: dawn.mccleskey@gsa.gov
