author: DigitalGov Search
title: DigitalGov Search
url: http://search.digitalgov.gov
permalink: /:categories/:title.html
lsi: false
highlighter: pygments
markdown: rdiscount
exclude: [.gitignore, .rvmrc, Gemfile, Gemfile.lock, README.md, Rakefile, config.rb, sass, vendor]

# plugin config
paginate_per_page: 10
posts_paginate_path: blog/page:num
posts_paginate_layout: paginate
posts_tag_layout: tag
