auto: true
permalink: /blog/:title.html
lsi: false
pygments: true
exclude: [Gemfile, Gemfile.lock, config.rb, sass]
server: true

# plugin config
paginate_per_page: 10
posts_paginate_path: blog/page:num
posts_paginate_layout: paginate
posts_tag_layout: tag